// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

// stimulusをセット
import ConversationStepController from "./conversation_step_controller"
application.register("conversation-step", ConversationStepController)

import BubbleFadeController from "./bubble_fade_controller"
application.register("bubble-fade", BubbleFadeController)

import WelcomeStepsController from "./welcome_steps_controller"
application.register("welcome-steps", WelcomeStepsController)

import SnackReactionController from "./snack_reaction_controller"
application.register("snack-reaction", SnackReactionController)

import SnackBaseController from "./snack_base_controller"
application.register("snack-base", SnackBaseController)

import SnackLoadingController from "./snack_loading_controller"
application.register("snack-loading", SnackLoadingController)

import DiaryModalController from "./diary_modal_controller"
application.register("diary-modal", DiaryModalController)