// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

// stimulusをセット
import ConversationStepController from "./conversation_step_controller"
application.register("conversation-step", ConversationStepController)

import WelcomeStepsController from "./welcome_steps_controller"
application.register("welcome-steps", WelcomeStepsController)

import SnackReactionController from "./snack_reaction_controller"
application.register("snack-reaction", SnackReactionController)